### PR TITLE
runner: sanitize untrusted VT sequences at the PTY output trust boundary (OSC 52 strip + title/hyperlink scrub)

### PR DESCRIPTION
**Pull request by jspinak**
## Summary

Hardens the in-app terminal at the **PTY-output trust boundary**. Terminal output is untrusted — it is whatever a child process (or a remote SSH host, or a `cat`'d file) emits. This adds `VtSanitizeHook` (`terminal::vt_sanitize`), an `OutputHook` on the existing interceptor pipeline that runs **first** on every PTY chunk, before the grid parser, the scrollback tee, and the frontend emit (the `session.rs` reader thread → `interceptor.process` path, untouched here). One pass sanitizes every downstream consumer at once.

Implements the VETTED plan `2026-06-13-terminal-vt-output-sanitization` (subset adopted from the `FurbySoup/quell` scout: strip-clipboard + sanitize-title).

## Classification (default = ALLOW pass-through)

- **STRIP entirely** — **OSC 52** (`ESC ] 52 ; … ST|BEL`), clipboard set/query. Arbitrary terminal output must never be able to silently overwrite or exfiltrate the operator's system clipboard. **This is the headline security fix.**
- **SANITIZE** (keep the sequence, scrub C0/C1/DEL control bytes from the payload, preserve introducer + terminator) — **OSC 0/1/2** (window/icon title) and **OSC 8** (hyperlink), so a title/URI can't smuggle embedded escape sequences. (Grid consumes OSC 0/2 today; OSC 1/8 scrubbing is harmless future-proofing.)
- **ALLOW untouched** — everything else: **OSC 633** (shell integration), DEC `?2026` (synchronized output — the #572 sync-frame coalescer depends on it), `?1049` (alt screen), `?25` (cursor visibility), all SGR/colors, cursor movement, bracketed paste, DCS, and all ordinary CSI/printable output.

Per the plan's open question, device-status/attribute **queries** (DSR/DA/DECRQSS) are **NOT** stripped — they're rare in output and stripping risks breaking apps that round-trip them; OSC 52 + title scrub covers the real abuse.

## Split-sequence carry

A target sequence can straddle two `process()` calls (PTY reads on arbitrary byte boundaries). In-progress, not-yet-emitted escape bytes are held in **per-terminal carry state** keyed by `terminal_id`. Since `OutputHook::process` is `&self` (the trait is `Send + Sync`), the carry map uses interior mutability: `Mutex<HashMap<String, Carry>>`. A split OSC 52 is fully removed; a split `?2026h` / OSC 633 passes through intact; two terminal_ids never cross-contaminate. No-ESC chunks take an allocation-free fast path (single ESC scan, return input).

## Escape hatch

Default-ON, gated by env **`QONTINUI_TERMINAL_SANITIZE`** (mirrors the `QONTINUI_COMMIT_LINEAGE_REPORT` idiom). Set to `0`/`false`/`off` to disable — the hook is then simply not registered (raw stream for debugging). Read once at hook construction in `main.rs`, registered right alongside `UsageLimitWatchHook`. No frontend↔Rust bridge.

## Files

- `src-tauri/src/terminal/vt_sanitize.rs` — new module: `VtSanitizeHook` + `OutputHook` impl, scanner, carry state, 26 unit tests.
- `src-tauri/src/terminal/mod.rs` — register the module.
- `src-tauri/src/main.rs` — register the hook (env-gated) next to `UsageLimitWatchHook`.

No edits to `session.rs`/`manager.rs` (the #572 reader body), so this is independent of #572.

## Verification

- `cargo check` ✅, `cargo clippy --all-targets -- -D warnings` ✅ (clean), `cargo test … vt_sanitize` ✅ **26/26 passed**. Pre-push `cargo fmt + clippy` gate passed.
- Tests cover: OSC 52 stripped (BEL + ST); OSC 633/0/2/SGR/`?2026h`/`?2026l`/`?1049h`/bracketed-paste/DCS preserved byte-for-byte; OSC 0/8 control-byte scrub; split-sequence carry (OSC 52 removed, `?2026h`/OSC 633 preserved); per-terminal isolation; binary/UTF-8 passthrough; idempotence.
- **Temp-runner build:** `cargo build succeeded` for this branch in a supervisor spawn-test (the Rust change compiles in a real build). On-page OSC-52 absence check: see PR comment (temp-runner frontend rebuild is environment-flaky on this box independent of this Rust-only change).

### CODE REVIEW

**Comment by jspinak** [comment]
### Temp-runner verification note

**Rust build: PASS.** A supervisor `spawn-test` (`rebuild:true`) of this branch reported **`cargo build succeeded`** — `VtSanitizeHook` and its registration compile in a real release-style build alongside the existing `UsageLimitWatchHook` / `AutoResponseWatchHook` pipeline.

**Live on-page OSC-52 write/buffer check: BLOCKED by a pre-existing frontend toolchain skew on this box, unrelated to this Rust-only change.** The spawn-test failed in `pnpm run build` (`tsc` exit 2) with:

```
src/components/navigation/Sidebar.tsx(111,3): error TS2305:
Module '"@qontinui/navigation"' has no exported member 'setShowHiddenItems'.
```

That error is in `Sidebar.tsx` (introduced by #569 `dc830800` "demote workflow-authoring nav", which is in this branch's base `ea55b8a7`), not in any file this PR touches — this PR changes **only** 3 Rust files (`main.rs`, `terminal/mod.rs`, `terminal/vt_sanitize.rs`) and zero frontend files. The shared (junctioned) `node_modules/@qontinui/navigation` is pinned to published `0.1.1`, which predates the `setShowHiddenItems` export the merged base now imports — a monorepo publish/install ordering issue. Because the frontend can't build, the supervisor (correctly) refuses to promote the slot to a runnable binary, so a live terminal couldn't be created on the temp runner to write the OSC-52 bytes and read `/terminals/<id>/buffer`.

**The equivalent assertions are covered byte-for-byte by the unit tests** (26/26 pass):
- `osc52_stripped_bel` / `osc52_stripped_st` / `osc52_query_stripped` — OSC 52 absent from output (the on-page "absent from buffer" assertion).
- `sgr_preserved` / `mixed_stream` — `ESC[31mRED ESC[0m` survives intact (the on-page "RED + SGR survives" assertion).
- `osc52_split_across_calls_fully_removed` + `per_terminal_carry_isolation` — the split-sequence carry path the live write would exercise.

The PTY reader feeds `interceptor.process(...)` output directly into the grid + scrollback (`session.rs`), and the buffer/`strip_ansi` surfaces read from that same scrollback, so the unit-level "stripped before it reaches scrollback" guarantee is exactly what the on-page buffer check would observe.

**Comment by jspinak** [comment]
### Update (b793523d): added carry cap + verification status

**Carry-cap fix.** A follow-up commit caps the per-terminal in-progress-sequence carry at 1 MiB. `scan_osc`/`scan_csi` return `Incomplete` with no length bound, so input that opens an escape sequence and never terminates it — the realistic trigger is `cat`-ing a binary file (lone `ESC [` / `ESC ]` + a long non-terminator run) — would otherwise grow the carry without bound in the hot reader path (a memory-DoS surface this hook would *introduce*). On overflow the buffered bytes are flushed as pass-through (matches pre-hook behavior for binary garbage → no data loss; an unterminated/over-cap OSC 52 still can't set the clipboard since xterm caps OSC payloads too). Added `over_cap_unterminated_sequence_is_flushed_not_unbounded`.

**Verification.**
- 27 unit tests pass: OSC 52 stripped incl. split-across-`process()`-calls; per-terminal carry isolation; over-cap flush; SGR / OSC 633 / `?2026` / `?1049` preserved byte-for-byte; title + OSC 8 control-byte scrub; idempotence.
- `cargo clippy --all-targets -- -D warnings` clean; `cargo build` **succeeds in the supervisor build pool**.
- **Live temp-runner OSC-52 check is BLOCKED by an unrelated breakage on `main`:** `Sidebar.tsx` (from #569) imports `setShowHiddenItems`, which the lockfile-pinned `@qontinui/navigation@0.1.1` does not export → `pnpm run build` (tsc) fails → the supervisor refuses to spawn a runner with a broken frontend. This is independent of this Rust-only change (which touches zero frontend files) and is being flagged separately; it blocks all temp-runner frontend builds + the next primary rebuild.

**Comment by jspinak** [comment]
### Correction + live verification PASSED

My earlier comment said the live temp-runner check was blocked by a "main-frontend breakage." **That was wrong — main is healthy.** The real cause was a verification-method artifact on my side: the test worktree's `node_modules` was junctioned from a primary checkout holding a stale `@qontinui/navigation@0.1.1`, while the lockfile pins **0.1.3** (bumped by #569). A clean `pnpm install` in the worktree resolved 0.1.3 and the frontend built normally.

**Live OSC-52 verification PASSED** on a temp runner built from this branch (buildId `b793523d`, isolated, never the primary):
- A PowerShell command *emitted* a real OSC 52 clipboard sequence + an SGR-red sequence to stdout.
- The scrollback buffer (post-sanitize, tee'd in `session.rs`) has the **OSC 52 escape (`\x1b]52`) stripped**, while the **SGR (`\x1b[31m`) and `RED` text are preserved** — exactly the intended classification, end-to-end through the real reader → `interceptor.process` → scrollback path.

Apologies for the false alarm on main in the prior comment.
