### PR TITLE
fix(file-activity): port fetchLockInfo from dropped apiBaseUrl() to resolvePort()

### PR DESCRIPTION
**Pull request by jspinak**
Main is red — `tsc --noEmit` fails on every platform with:

    src/components/productivity/fileActivityApi.ts(156,18):
    error TS2304: Cannot find name 'apiBaseUrl'.

## Root cause: merge-race between two sibling PRs

| Time (UTC, 2026-05-12) | SHA | PR | What |
|---|---|---|---|
| 06:05:53 | `7cdcade44` | #93 | Adds `fetchLockInfo` calling `apiBaseUrl()` — a function that existed when its branch's CI ran |
| 06:07:35 | `56affd9b5` | #92 | Drops `apiBaseUrl()`, ports every then-existing caller (just `fetchHeatmap`) to `resolvePort()`. CI was clean on its own branch because #93's new caller hadn't merged yet at the time #92's branch HEAD was last tested |

GitHub merged both without re-running CI on the post-#93 state of #92, so main shipped with a dangling reference. I caught it because PR #100 (docs-only) inherited the failure on every OS test job.

## Fix
One-line change — same shape PR #92 used for the other caller (`fetchHeatmap` at line 131): inline the `http://127.0.0.1:${resolvePort()}/...` form. `resolvePort` is already imported at line 22.

```diff
-  const url = `${apiBaseUrl()}/file-locks/info`;
+  const url = `http://127.0.0.1:${resolvePort()}/file-locks/info`;
```

## Test plan
- [x] Local `npx tsc --noEmit` clean
- [ ] CI green on all three OS jobs
- [ ] Once merged, PR #100's CI should auto-recover (no rerun needed since it's a fresh PR that'll pick up the new main when its checks fire next)

## Why this kind of race happens
PR-level CI checks the branch HEAD at approval time, not at merge time. When two PRs both pass CI individually and merge in quick succession, GitHub's branch-protection rules don't re-verify the post-merge state. Branches that drop a symbol the merged-sibling branch added a caller of slip through. Mitigation options for the maintainer (not addressed in this PR): enable "require branches to be up to date before merging" on the branch protection rule, or use a merge queue.

### CODE REVIEW

**Comment by jspinak** [comment]
## Post-mortem suggestion: prevent the next merge race

This PR fixed the symptom of a class of bug that GitHub's default branch protection doesn't catch. The root cause:

> PR-level CI checks the branch HEAD at approval time, not at merge time. When two PRs both pass CI individually and merge within seconds, GitHub doesn't re-verify the post-merge state of either.

Two mitigations available in repo settings — both close this class:

**Option A — "Require branches to be up to date before merging"** (one-click toggle on the `main` branch protection rule). Every PR must merge `main` (or rebase) into its branch before the merge button enables, which retriggers CI on the merged state. Cost: a manual `Update branch` click (or `gh pr update-branch`) on each PR if main moves. Today's #93 → #92 race would've required #92 to update + re-CI; the typecheck failure would've surfaced on the PR, not in main.

**Option B — GitHub Merge Queue** (more invasive but more powerful). GitHub batches mergeable PRs and runs CI on the post-merge tree before each one lands. No manual intervention needed. Worth it on repos with high merge throughput; today's window had three PRs (#92, #93, plus an in-flight one) merging within minutes.

Either is a strict improvement. (A) is the smaller behavior change and the one I'd recommend first — you can always layer (B) later.

Today's outage was ~25 minutes from broken-main to fix-merged, but every PR opened against `main` during that window inherited the red CI (mine, #100, did). Memory entry saved at `proj_co_merge_race_risk.md` so future-me catches the pattern before re-deriving it from a flaky CI run.

— Claude Code
